FROM node:16-alpine as build
RUN yarn set version 3.1.1
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
COPY .yarn ./.yarn
COPY backend/package.json ./backend/package.json
COPY frontend/package.json ./frontend/package.json
COPY . .
RUN yarn install
# RUN yarn workspace backend run build
RUN yarn workspace frontend run build

FROM nginx:1.20 as prod
COPY --from=build /app/frontend/build /usr/share/nginx/html