enum GameState {
  LOBBY
  ACTIVE
  PAUSED
  STOPPED
}

type Game {
  id: ID!
  state: GameState!
}

type GameConfiguration {
  date: String!
  cluster: String!
  game: Game
}

type Query {
  gameConfig: GameConfiguration!
}

input ConnectionRequest {
  username: String
  gameId: String
  playerId: String
}

type Mutation {
  connect(request: ConnectionRequest): GameConfiguration!
}

type Subscription {
  game: Game
}
