enum GameState {
  LOBBY
  TESTING
  ACTIVE
  PAUSED
  STOPPED
}

type Game {
  id: ID!
  state: GameState!
}

input GameFilter {
  state: GameState
}

type Query {
  games(filter: GameFilter): [Game!]!
}

type Subscription {
  game(id: ID!): Game
}

extend type Mutation {
  setGameState(state: GameState!): [Game!]!
}