type Player {
  id: ID!
  username: String!
  game: Game!
}

extend type Game {
  players: [Player!]!
}

extend type Query {
  player(id: ID!): Player
}

input ConnectionRequest {
  gameId: String
  playerId: String
  username: String
}

type Mutation {
  connectPlayer(request: ConnectionRequest): Player!
}
